FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1

COPY ERP-api.csproj .
RUN dotnet restore

CMD ["dotnet","watch","run","--urls","http://0.0.0.0:8080"]
